# Generated by Django 3.1.4 on 2021-02-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datawidget',
            name='python_script',
        ),
        migrations.AlterField(
            model_name='datawidget',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
