# Generated by Django 3.1.4 on 2021-01-28 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210128_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datawidget',
            old_name='sql',
            new_name='python_script',
        ),
    ]
