# Generated by Django 3.1.4 on 2021-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210128_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='datawidget',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
