# Generated by Django 3.1.4 on 2021-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('amount', models.BigIntegerField()),
                ('comments', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'cash_flow',
            },
        ),
    ]
