# Generated by Django 3.1.4 on 2021-01-18 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_widget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
