# Generated by Django 3.1.4 on 2021-01-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_widget', '0002_auto_20210118_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
    ]
